import { StyleSheet } from 'react-native';
import { colors, spacing, radii, typography, shadows } from '@/services/constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.backgroundSoft,
    padding: spacing.xl,
  },
  iconContainer: {
    marginBottom: spacing.xl,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.badgeSoft,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    ...typography.h1,
    marginBottom: spacing.md,
  },
  subtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.xxl,
    lineHeight: 24,
  },
  loginButton: {
    flexDirection: 'row',
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.xxl + spacing.lg,
    paddingVertical: spacing.lg,
    borderRadius: radii.md,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.lg,
    ...shadows.button,
  },
  loginButtonText: {
    color: colors.background,
    fontSize: 18,
    fontWeight: '600',
    marginLeft: spacing.sm,
  },
  registerButton: {
    backgroundColor: colors.backgroundSoft,
    paddingHorizontal: spacing.xxl + spacing.lg,
    paddingVertical: spacing.lg,
    borderRadius: radii.md,
    width: '100%',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.primary,
  },
  registerButtonText: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: '600',
  },
  authenticatedContainer: {
    flex: 1,
    backgroundColor: colors.backgroundSoft,
  },
  scrollContent: {
    paddingBottom: spacing.xxl,
  },
  userHeader: {
    alignItems: 'center',
    padding: spacing.xxl,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  userIconContainer: {
    marginBottom: spacing.lg,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.badgeSoft,
    justifyContent: 'center',
    alignItems: 'center',
  },
  userName: {
    ...typography.h2,
    marginBottom: spacing.xs,
  },
  userEmail: {
    fontSize: 15,
    color: colors.textSecondary,
  },
  optionsContainer: {
    marginTop: spacing.sm,
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.lg,
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  optionIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.badgeSoft,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.lg,
  },
  optionText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '500',
    color: colors.textPrimary,
  },
  logoutButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    margin: spacing.xl,
    padding: spacing.lg,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.danger,
    backgroundColor: colors.card,
    ...shadows.card,
  },
  logoutButtonText: {
    color: colors.danger,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: spacing.sm,
  },
});
